name: Rust

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Cache deps
        uses: actions/cache@v2
        env:
          cache-name: cache-deps
        with:
          path: |
            ~/.cargo
            target
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true
      - name: Test
        run: cargo test
      - name: Build
        run: cargo build --release
      - uses: actions/setup-node@v2
      - name: build frontend
        run: cd frontend && yarn install && yarn build && cd ..
      - name: Publish docker image to Github Packages
        uses: HurricanKai/Publish-Docker-Github-Action@master
        with:
          name: docker.pkg.github.com/nikitavbv/my-k8s-dashboard/my-k8s-dashboard
          registry: docker.pkg.github.com
          username: ${{ secrets.GITHUB_TOKEN }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish docker image to Docker Hub
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: nikitavbv/my-k8s-dashboard
          registry: docker.io
          username: nikitavbv
          password: ${{ secrets.docker_hub_token }}
          tags: "latest,0.1.0"
